import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { Session } from '@statebeats/sdk';
test('browser worker plays, pauses, exports a verified replay and restarts', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(String(error)));
  await page.goto('/');
  await expect(page.locator('#play')).toBeEnabled();
  await page.locator('#settings').click();
  await page.locator('#speed').selectOption('4');
  await page.locator('#close-settings').click();
  await page.getByRole('button', { name: /Agent arena/ }).click();
  await page.locator('#watch').click();
  await expect(page.locator('#hud')).toBeVisible();
  await page.locator('#pause').click();
  await expect(page.locator('#pause-panel')).toBeVisible();
  const score = await page.locator('#score').textContent();
  await page.waitForTimeout(300);
  expect(await page.locator('#score').textContent()).toBe(score);
  await page.locator('#resume').click();
  await expect(page.locator('#results')).toBeVisible({ timeout: 20000 });
  await expect(page.locator('#result-stats')).toContainText('800');
  await expect(page.locator('#result-detail')).toContainText('0 missed');
  const download = page.waitForEvent('download');
  await page.locator('#export-replay').click();
  const file = await download;
  const replay = JSON.parse(await readFile((await file.path())!, 'utf8'));
  expect((await Session.verifyReplay(replay)).verified).toBe(true);
  await page.locator('#again').click();
  await expect(page.locator('#results')).toBeHidden();
  await page.locator('#pause').click();
  await page.locator('#home').click();
  await expect(page.locator('#lobby')).toBeVisible();
  expect(errors).toEqual([]);
});
test('desktop mouse input earns a hit and finishes a real sequence', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.goto('/');
  await expect(page.locator('#play')).toBeEnabled();
  await page.locator('#settings').click();
  await page.locator('#speed').selectOption('4');
  await page.locator('#close-settings').click();
  await page.getByRole('button', { name: /Agent arena/ }).click();
  await page.locator('#play').click();
  await expect(page.locator('#hud')).toBeVisible();
  await page.mouse.move(640, 537);
  await page.mouse.down({ button: 'left' });
  await expect(page.locator('#score')).not.toHaveText('0');
  await page.mouse.up({ button: 'left' });
  await expect(page.locator('#results')).toBeVisible({ timeout: 20000 });
  await expect(page.locator('#mode-label')).toHaveText('DESKTOP SESSION');
});
